version: '3.4'
services:
  jira:
    build:
      dockerfile: Dockerfile
    container_name: jira-servicedesk-srv
    environment:
      - TZ='Asia/Ho_Chi_Minh'
    depends_on:
      - jira_servicedesk
    ports:
      - "8080:8080"
    volumes:
      - jira_servicedesk_data:/var/jira
      - jira_servicedesk_core:/opt/jira
      - dbconfig.xml:/var/atlassian/application-data/jira/dbconfig.xml
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - network-bridge
  jira_servicedesk:
    image: postgres:13
    container_name: postgresql-jira-servicedesk
    env_file:
      - database-jira.env
    # ports:
    #   - "5432:5432"
    volumes:
      - database_jira_servicedesk:/var/lib/postgresql/data/
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge
volumes:
  jira_servicedesk_data:
    external: false
  database_jira_servicedesk:
  jira_servicedesk_core:
  